safe: false
source: .
destination: ./_site
plugins_dir: ./_plugins
lsi: true
highlighter: rouge
markdown: kramdown
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', 'vendor']

url: http://10th-ndn-hackathon.named-data.net
baseurl:

plugins:
  - jekyll-assets

deadlines:
        - name: Submission deadline
          date: Wednesday, Oct 14th, 2020 
        - name: Acceptance notification
          date: Friday, Oct 16th, 2020

# Configuration for permalink
permalink: /:page.html

# Configuration for site
title: 10th Named Data Networking (NDN) Hackathon (Virtual)
short_title: 10th NDN Hackathon 
description: Oct 17-18 , 2020
author: 10th NDN Hackathon Organizing Committee
email: 10th-ndn-hackathon@named-data.net

# Configuration for blog
lang: en
columns: 3
date_format: "%B %d, %Y"
truncate_len: 200

# Configuration for navbar.html
navbar_list:
  - name: Home
    link: /
  - name: Committees
    link: /committees.html
  - name: Terms
    link: /terms.html
  - name: <b>HACKS</b>
    link: /hacks.html
  - name: Program
    link: /program.html
  - name: Judging
    link: /judging.html

asides:
    github: true
    tweets: false
    archive_tabs: false

google_plus_one:
    size: medium

twitter:
    username: NamedData
    count: 5
    exclude_replies: true
    show_screen_name: true
    show_follower_count: false
    widget_id: 698294519054278656

github:
   username: 10th-ndn-hackathon
   count: 10000

assets:
  cache: .sass-cache
  features:
    automatic_img_size: false

  sources:
    - _assets/css
    - _assets/images
    - _assets/fonts
    - _assets/js
    - _assets/bower
    - _assets/files

  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
